version: '2'
services:
  dispielemanufaktur:
    container_name: dispielemanufaktur
    image: 'ghcr.io/sparkobbable/deutschirischespielemanufaktur:latest'
      # args:
      #   REACT_APP_BACKEND_URL: "http://localhost:8080"
    depends_on:
      - api
    volumes:
      - '/app/node_modules'
    ports:
      - 82:80
  dispielemanufaktur-dev:
    container_name: dispielemanufaktur-dev
    image: 'ghcr.io/sparkobbable/deutschirischespielemanufaktur:dev'
    volumes:
      - '/app/node_modules'
    ports:
      - 83:80
  api:
    container_name: dispiele-backend
    image: 'ghcr.io/sparkobbable/dispiele-backend:latest'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dispiele
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - ALLOWED_ORIGIN=http://localhost
    ports:
      - 8081:8080
  db:
    image: 'postgres:14.2'
    container_name: dispieleDB
    environment:
      - POSTGRES_DB=dispiele
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./dispiele/postgres-data:/var/lib/postgresql/data
      # - ./dispiele/postgres/schema.sql:/docker-entrypoint-initdb.d/a_init.sql
      # - ./dispiele/postgres/data.sql:/docker-entrypoint-initdb.d/b_data.sql