version: "2"
services:
    dispielemanufaktur:
        container_name: dispielemanufaktur
        image: "ghcr.io/sparkobbable/deutschirischespielemanufaktur:latest"
        depends_on:
            - api
        volumes:
            - "/app/node_modules"
        ports:
            - 82:80
    dispielemanufaktur-dev:
        container_name: dispielemanufaktur-dev
        image: "ghcr.io/sparkobbable/deutschirischespielemanufaktur:dev"
        depends_on:
            - api-dev
        volumes:
            - "/app/node_modules"
        ports:
            - 83:80
    api:
        container_name: dispiele-backend
        image: "ghcr.io/sparkobbable/dispiele-backend:latest"
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dispiele
            - SPRING_DATASOURCE_USERNAME=${DB_USER}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - SPRING_MAIL_USERNAME=${EMAIL_USER}
            - SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD}
        ports:
            - 8081:8080
    api-dev:
        container_name: dispiele-backend-dev
        image: "ghcr.io/sparkobbable/dispiele-backend:dev"
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dispiele
            - SPRING_DATASOURCE_USERNAME=${DB_USER}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - SPRING_MAIL_USERNAME=${EMAIL_USER}
            - SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD}
        ports:
            - 8081:8080
    db:
        image: "postgres:14.2"
        container_name: dispieleDB
        environment:
            - POSTGRES_DB=dispiele
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5050:5432
        volumes:
            - ./dispiele/postgres-data:/var/lib/postgresql/data
            # - ./dispiele/postgres/schema.sql:/docker-entrypoint-initdb.d/a_init.sql
            # - ./dispiele/postgres/data.sql:/docker-entrypoint-initdb.d/b_data.sql
